version: '3.8'

services:
  identity:
    container_name: identity-api
    image: latest/identity-api
    restart: always
    build:
      context: ../../../services
      dockerfile: ./identity/Dockerfile
    ports:
      - "5000:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
  projects:
    container_name: projects-api
    image: latest/projects-api
    restart: always
    build: 
      context: ../../../services
      dockerfile: ./projects/Dockerfile
    ports:
      - "5001:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
  jobs:
    container_name: jobs-api
    image: latest/jobs-api
    restart: always
    build:
      context: ../../../services
      dockerfile: ./jobs/Dockerfile
    ports:
      - "5002:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
  builds:
    container_name: builds-api
    image: latest/builds-api
    restart: always
    build:
      context: ../../../services
      dockerfile: ./builds/Dockerfile
    ports:
      - "5003:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
  buildScheduler:
    container_name: build-scheduler-api
    image: latest/build-scheduler-api
    restart: always
    build:
      context: ../../../services
      dockerfile: ./buildScheduler/Dockerfile
    ports:
      - "5004:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
  buildWorker:
    container_name: build-worker-api
    image: latest/build-worker-api
    restart: always
    build:
      context: ../../../services
      dockerfile: ./buildWorker/Dockerfile
    ports:
      - "5005:80"
    networks:
      - blditapi
    volumes:
      - bldithome:/app/bldit
#  files:
#    container_name: files-api
#    image: latest/files-api
#    restart: always
#    build:
#      context: ../../../services
#      dockerfile: ./files/Dockerfile
#    volumes:
#      - bldithome:/app/bldit
#    networks:
#      - blditapi
  bldit-api:
    image: latest/bldit-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ../../../api
      dockerfile: ./BldIt.Api/Dockerfile
    ports:
      - "4000:80"
    networks:
      - blditapi
    depends_on:
      - identity
      - projects
      - jobs
      - builds
      - buildScheduler
      - buildWorker
      # - files
  
volumes:
  bldithome:
networks:
  blditapi: